LaunchArgumentIndieV2:4
WindowHeight:470
WindowWidth:810
LaunchFolderSelect:$.minecraft\
LaunchVersionSelect:Bunker Server AOT
LaunchArgumentTitle:Bunker Server AOT
LaunchArgumentInfo:Bunker Server AOT
LaunchArgumentWindowType:3
UiLauncherTransparent:600
UiLauncherLogo:False
UiBackgroundColorful:True
UiLogoType:0
SystemSystemActivity:1
UiHiddenFunctionHidden:False
UiHiddenOtherVote:True
UiHiddenOtherTest:True
UiHiddenOtherFeedback:True
UiHiddenOtherAbout:True
UiHiddenOtherHelp:True
UiHiddenPageOther:True
UiHiddenPageSetup:True
UiHiddenSetupLaunch:True
UiHiddenSetupSystem:True
UiHiddenSetupUi:True
UiHiddenSetupLink:False
LoginPageType:0
LaunchArgumentWindowWidth:1600
LaunchArgumentWindowHeight:1000
