#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jan 14 23:50:04 HKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=4
shaderPack=Sundial Core Dev Packup 2025-12-02.zip
